---
- hosts: localhost
  vars:
    ansible_python_interpreter: /bin/python3
    gather_facts: no
    project_id: "P00"                        ## <-- 개인별 프로젝트 ID값 사용 
    vcenter_hostname: "172.16.1.10"
    vcenter_username: "s00@vclass.reca3"     ## <-- 개인별 vSphere 계정 사용 
    vcenter_password: "VMware1!"
    datacenter_name: "RECA3"
    esxi_hostname: "esxi-05.vclass.reca3"    ## <-- 개인별 실습 물리서버 사용 
    esxi_username: "root"
    esxi_password: "VMware1!"
    public_net:  "VM-172.16.1.x"
    private_net: "{{ project_id + '-Openshift' }}"
    folder_name: "{{ '/RECA3/vm/4.Projects/' + project_id }}"
    datastore_name: "RECA3-05"              ## <-- 개인별 실습 서버의 저장소
    iso_folder: '[RECA3-05]\ISOs\'          ## <-- 개인별 실습 서버의 ISO 폴더 경로

  tasks: 
    - name: 08. Add Disks to Bastion 
      community.vmware.vmware_guest_disk:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: 'false'
        datacenter: '{{datacenter_name}}'        
        name: "{{ project_id + '-Bastion'}}"
        disk:
        - size_gb: 200
          type: thin
          datastore: '{{ datastore_name }}'
          state: present
          scsi_controller: 0
          unit_number: 1
          scsi_type: 'paravirtual'
          disk_mode: 'persistent'
      delegate_to: localhost
      register: disk_facts
